version: "3"

services:
  react-portfolio:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - ./.env
